### ISSUE TITLE
client-go does not support getting the resources in a single namespace without going to the cluster scope

### ISSUE THREAD

**Issue by LennDG** [kubernetes/client-go#1026]
I am trying to list all secrets in the namespace for which the RBAC Role is set up
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: foo-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
 ```
 
 My current code is:
 ```golang
 secretsClient := clientset.CoreV1().Secrets("foo-system")

var opts metav1.ListOptions
opts.LabelSelector = "switch-id in (" + switchID + ")"

var secrets *corev1.SecretList
secrets, err := secretsClient.List(ctx, opts)
```

My understanding of client-go tells me that this should list only the secrets in the "foo-system" namespace. However, when this code is executed I get this error:
`Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:foo-system:foo-controller-manager" cannot list resource "secrets" in API group "" at the cluster scope`

Is there a way for client-go to bypass listing the secrets at cluster scope?
