### ISSUE TITLE
Provide helper functions to map/filter/reduce/iterate through e.g. container environment variables

### ISSUE THREAD

**Issue by tappoz** [kubernetes/client-go#1044]
This could help in narrowing down the boiler-plate code on the client side that is using the SDK:

```go
// https://pkg.go.dev/k8s.io/api@v0.23.1/core/v1#Container
func _getContainerEnvVar(container apiv1.Container, envVarName string) (*string, error) {
	// https://pkg.go.dev/k8s.io/api@v0.23.1/core/v1#EnvVar
	for _, envVar := range container.Env {
		if envVar.Name == envVarName {
			// log.Printf("container env var %s: %+v", envVarName, envVar.Value)
			return &envVar.Value, nil
		}
	}
	return nil, fmt.Errorf("cannot find env var %s", envVarName)
}
```

It could help when there's a YAML list like the one for environment variables:

```yaml
              env:
                - name: FOO_VAR
                  valueFrom:
                    configMapKeyRef:
                      name: my-env
                      key: FOO_VAR_KEY
                - name: BAR_VAR
                  value: "bar-value"
```

But the pattern could be applied to a variety of scenarios that deal with iterations.

Some examples using the code above could also help when getting started with the SDK as clicking through the docs and sub-packages here https://pkg.go.dev/k8s.io/api sometimes is a bit overwhelming.

Is it considered acceptable adding this kind of functionality to the Go SDK, or is this considered to be left to the user following the Go principles of not adding map/filter/reduce leaving `for` loop to whoever is using the SDK?
