### ISSUE TITLE
kubectl diff like in client-go

### ISSUE THREAD

**Issue by ltmleo** [kubernetes/client-go#1055]
Hello,

There is a simple way to use client-go to diff a given manifest with the live version, like `kubectl diff -f pod.yaml` do? 

example:

```
test := """
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
"""
diff, _ := Diff(test)
fmt.Print(diff)
```

returns:

```
--- /tmp/LIVE-730417402/v1.Pod.default.nginx     2022-02-02 18:16:43.849600242 -0300
+++ /tmp/MERGED-381187601/v1v1.Pod.default.nginx      2022-02-02 18:16:43.893611257 -0300
@@ -8,7 +8,7 @@
  containers:
  - name: nginx
 +   image: nginx:1.14.3
 -   image: nginx:1.14.2
    ports:
    - containerPort: 80
```
Thank you so much!
