### ISSUE TITLE
The latest version of lngress creates an error

### ISSUE THREAD

**Issue by dongliangde** [kubernetes/client-go#1061]
IngressClass.networking.k8s.io \"name\" is invalid: spec.controller: Required value
****
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    bpp: name
  name: name
  namespace: testyaml
spec:
  defaultBackend:
    service:
      name: name
      port:
        number: 10215
  ingressClassName: nginx
  rules:
    - host: xx.xx.xx
      http:
        paths:
          - backend:
              service:
                name: name
                port:
                  number: 10215
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - xx.xx.xx
      secretName: xx.xx
```
