### ISSUE TITLE
How to read and write istio crd

### ISSUE THREAD

**Issue by baojiliu** [kubernetes/client-go#1136]
I have a ```yaml``` file like:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: echo-vs
spec:
  hosts:
    - echo
  gateways:
    - main-gateway
  http:
    - match:
        - uri:
            prefix: /echo
      route:
        - destination:
            host: echo
            port:
              number: 8000
```
I want to modify some things like prefix and save to yaml file.
Looking forward to any suggestions thanks
