### ISSUE TITLE
client creation failing intermittently with "Unauthorized" error in pod

### ISSUE THREAD

**Issue by shubhamyelikar** [kubernetes/client-go#1158]
We are facing intermittent issue in k8s go-client creation in pod using client-go[https://github.com/kubernetes/client-go] at our customer side. 
K8s client creation is randomly failing with "Unauthorized" error in some pods.

Here is sample code snippet we are using for k8s client creation,

```
package main

import (
    "context"
    "fmt"
    
    corev1 "k8s.io/api/core/v1"
    extClient "k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset"
    "k8s.io/apimachinery/pkg/api/meta"
    "k8s.io/apimachinery/pkg/runtime"
    "k8s.io/apimachinery/pkg/types"
    utilruntime "k8s.io/apimachinery/pkg/util/runtime"
    client "k8s.io/client-go/kubernetes"
    clientGoScheme "k8s.io/client-go/kubernetes/scheme"
    "k8s.io/client-go/rest"
    ctrl "sigs.k8s.io/controller-runtime"
    ctrlRuntime "sigs.k8s.io/controller-runtime/pkg/client"
    "sigs.k8s.io/controller-runtime/pkg/client/apiutil"
)

func main() {
    scheme := runtime.NewScheme()
    utilruntime.Must(clientGoScheme.AddToScheme(scheme))
    restConfig := ctrl.GetConfigOrDie()
    set, err := client.NewForConfig(restConfig)
    if err != nil {
        panic(err)
    }
    extSet, err := extClient.NewForConfig(restConfig)
    if err != nil {
        panic(err)
    }

    mapper, err := func(c *rest.Config) (meta.RESTMapper, error) {
        return apiutil.NewDynamicRESTMapper(c)
    }(restConfig)
    if err != nil {
        panic(err)
    }
    cl, err := ctrlRuntime.New(restConfig, ctrlRuntime.Options{
        Scheme: scheme,
        Mapper: mapper,
    })
    pod := &corev1.Pod{}
    err = cl.Get(context.Background(), types.NamespacedName{
        Namespace: "xyx",
        Name:      "abcd",
    }, pod)
    fmt.Println(err, set, extSet)
}

```

## K8s Version: 1.21

We are suspecting that somehow service account token is getting expired/corrupted that's why client-go is failing to create the k8s client. We even able to replicate the issue by updating invalid token in service account token, but we are not sure if the customer is facing the issue because of this reason and if yes, then why service account token is getting expired/corrupted.

## failed pod yaml:

```
apiVersion: v1
kind: Pod
metadata:
  name: abcd
  namespace: xyz
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep infinity
    image: image-name
    imagePullPolicy: IfNotPresent
    name: test
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - SYS_ADMIN
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: false
      runAsUser: 0
    volumeMounts:
    - mountPath: /sample
      name: nfs
    - mountPath: /tmp
      name: tmp-volume
    - mountPath: /proxy-certs
      name: proxy-ca-cert
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hh5l6
      readOnly: true
  imagePullSecrets:
  - name: f2d70900-3e63-4119--b8a9554b
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
  serviceAccount: f2d70900-3e63-4119-9b8b-17644e82eebe
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: eb941bb0-4802-4f9d-b6bd-242709f52474
  - emptyDir: {}
    name: tmp-volume
  - configMap:
      defaultMode: 420
      name: f2d70900-3e63-4119-9b8b-17644e82eebe
    name: proxy-ca-cert
  - name: kube-api-access-hh5l6
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
```
We had tried to replicate the issue in actual code flow using following steps but had no luck,

1. Tried by reducing expirationSeconds to 10m and added 10m sleep before running actual command.
2. `serviceAccountToken` is getting correctly updated in pod after expirationSeconds
3. Also tried using created client after expirationSeconds, this case is also working, client-go library handling this
