### ISSUE TITLE
Support specifying that proxy servers should not be used for cluster communication in kubeconfig

### ISSUE THREAD

**Issue by rhowe** [kubernetes/client-go#1161]
This is a request for the inverse of https://github.com/kubernetes/client-go/issues/351

Where environment variables contain proxy settings, it can be useful to specify that they should be ignored when communicating with the apiserver.

I thought of a couple of ways this could be implemented. The easiest, but perhaps more confusing to the user way would be to define a magic "no proxy" URL, which if configured as the proxy-url for a cluster would prevent proxy configuration taking place.

e.g.
```yaml
clusters:
- name: mycluster
  proxy-url: noproxy://
  certificate-authority-data: ...
  server: https://k8s.example.org
```

A more invasive, but perhaps less confusing way would be to introduce a new configuration value, along the lines of `ignore-proxy: true`. This would be mutually-exclusive with the `proxy-url` setting.

e.g.
```yaml
clusters:
- name: mycluster
  ignore-proxy: true
  certificate-authority-data: ...
  server: https://k8s.example.org
```
