### ISSUE TITLE
How to perform pre-verification when using dynamic client to create resources？

### ISSUE THREAD

**Issue by mark8s** [kubernetes/client-go#1226]
Hello everyone, I have a question.

When I was using client-go dynamic client, I found a phenomenon, the following code:
```
_, err = r.KubeDynamicClient.Resource(mapping.Resource).Namespace(namespace).Create(ctx, &unstruct, metav1.CreateOptions{})

```

I use the above code to create a crd resource. This crd resource is actually problematic. It has a wrong owner references in it, pointing to a cross-cluster crd resource (ShortCutRun). Its resource content is:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
   name: reviews
   namespace: bookinfo
   ownerReferences:
   - apiVersion: xxx
     kind: ShortCutRun
     name: canary-shortcutrun-sample
spec:
   host: reviews
   subsets:
   - labels:
       version: v1
     name: v1
   - labels:
       version: v2
     name: v2
   trafficPolicy:
     loadBalancer:
       simple: RANDOM
```

Therefore, when I use DynamicClient to create this resource, after execution, this resource (DestinationRule) does not appear in the cluster. The final reason is the wrong ownerreferences configuration. However, DynamicClient does not return any error, it returns a nil. It seems that the create or patch interface of DynamicClient has not been verified for resources?

I just want to ask now, is there any way or solution to solve this problem?

Does anyone know? Hope to get help.
