### ISSUE TITLE
TCP connections not reused when HTTP proxy-url is set

### ISSUE THREAD

**Issue by cedws** [kubernetes/client-go#1257]
In our corporate environment, we're only able to access our clusters via a HTTP proxy. We set the `proxy-url` field in our configs to do this. It looks something like this:

```
apiVersion: v1
kind: Config
clusters:
  - name: rancher-desktop
    cluster:
      server: https://127.0.0.1:6443
      proxy-url: http://localhost:5555
      certificate-authority-data: ...
      insecure-skip-tls-verify: false
...
```

I've noticed that interacting with the cluster through [k9s](https://github.com/derailed/k9s) is much slower when this proxy is in use compared to hitting the API server directly

I did a test on my personal machine with just Rancher Desktop and a basic [HTTP CONNECT proxy from a gist](https://gist.github.com/yowu/f7dc34bd4736a65ff28d).

If `proxy-url` is unset, the connections are reused as expected and new connections are not spawned from actions in k9s.

<img width="1383" alt="Screenshot 2023-05-19 at 18 18 31" src="https://github.com/kubernetes/client-go/assets/38229097/b8cd0173-e27d-423f-a9c8-944c9fe014ee">

When `proxy-url` is in use, I can see that significantly more TCP connections from the client are opened in Wireshark, as if they aren't being reused at all. Most actions in k9s like describing a pod open a new connection. The connections are also left open for a long time.

<img width="1375" alt="Screenshot 2023-05-19 at 18 16 51" src="https://github.com/kubernetes/client-go/assets/38229097/7a5ec0fc-c9f7-43ef-af7e-1dc484433e00">

I'm assuming this is a bug in client-go but could also be in k9s, not too sure yet. I would like to try and write a quick test program that retrieves pods or something since kubectl doesn't run for long enough to demonstrate if TCP connection pooling is working properly.
