### ISSUE TITLE
unable to create a deployment without replication controller

### ISSUE THREAD

**Issue by jzhu077** [kubernetes/client-go#137]
```
// Define Deployments spec.
	deploySpec := &v1beta1.Deployment{
		TypeMeta: unversioned.TypeMeta{
			Kind:       "Deployment",
			APIVersion: "extensions/v1beta1",
		},
		ObjectMeta: v1.ObjectMeta{
			Name: "binary-search",
		},
		Spec: v1beta1.DeploymentSpec{
			Replicas: int32p(1),
			Template: v1.PodTemplateSpec{
				ObjectMeta: v1.ObjectMeta{
					Name:   appName,
					Labels: map[string]string{"app": appName},
				},
				Spec: v1.PodSpec{
					Containers: []v1.Container{
						v1.Container{
							Name:  "nginx-container",
							Image: "nginx",
							VolumeMounts: []v1.VolumeMount{
								v1.VolumeMount{
									MountPath: "/usr/share/nginx/html",
									Name:      "shared-data",
								},
							},
						},
						v1.Container{
							Name:  "debian-container",
							Image: "debian",
							VolumeMounts: []v1.VolumeMount{
								v1.VolumeMount{
									MountPath: "/pod-data",
									Name:      "shared-data",
								},
							},
							Command: []string{
								"/bin/sh",
							},
							Args: []string{
								"-c",
								"echo Hello from the debian container > /pod-data/index1.html",
							},
						},
					},
					RestartPolicy: v1.RestartPolicyAlways,
					DNSPolicy:     v1.DNSClusterFirst,
					Volumes: []v1.Volume{
						v1.Volume{
							Name: "shared-data",
							VolumeSource: v1.VolumeSource{
								EmptyDir: &v1.EmptyDirVolumeSource{},
							},
						},
					},
				},
			},
		},
	}
```
```
// Implement deployment update-or-create semantics.
// c *kubernetes.Clientset
	deploy := c.Extensions().Deployments(namespace)
	_, err := deploy.Update(deploySpec)

```
I would like to do the same as following yaml file do and deploy it with client-go
```
restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: debian-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the debian container > /pod-data/index.html"]
```
The issue is I cannot create a deployment spec without creating replication controller along with it.I would not like to use replication controller because in my app, containers within a pod are used to complete a task and terminate the container when the task is completed so I would like to set restart policy to never to prevent any terminated container tries to restart. 
ps: I was following examples from https://github.com/timoreimann/kubernetes-goclient-example
