### ISSUE TITLE
Update gogo/protobuf dependency?

### ISSUE THREAD

**Issue by F21** [kubernetes/client-go#148]
I am using glide for dependency management and am importing` k8s.io/client-go` and `openzipkin\zipkin-go-opentracing`.

Both of these packages depend on `gogo/protobuf`. `zipkin-go-opentracing` does not use any dependency management, but assumes a version of `gogo/protobuf` with `const GoGoProtoPackageIsVersion2 = true`.

Since `k8s.io/client-go` uses godep, glide parses `Godeps.json` and sets `gogo/protobuf` to `e18d7aa8f8c624c915db340349aad4c49b10d173`, which is a really old version. The program then fails to compile because `zipkin-go-opentracing` expects a newer version of `gogo/protobuf`.

This is easily worked around by updating `glide.lock` to the right commit, but it is a bit annoying as there are bugs with glide on Windows where I need to remove the `/vendor` folder and `glide.lock` file in order to get some dependencies to install.

Would it be possible to update `gogo/protobuf` to a newer version? The one being used appears to be around a year old, and a stable version (`v.0.4`) was recently released.

**Comment by ericchiang** [comment]
There's a section at the bottom of the glide install docs: https://github.com/kubernetes/client-go/blob/master/INSTALL.md#glide

You can just set gogo/protobuf to a newer version in your glide.yaml file:

```yaml
package: ( your project's import path ) # e.g. github.com/foo/bar
import:
- package: k8s.io/client-go
  version: v2.0.0
# Use a newer version of gogo/protobuf even though client-go wants an old one.
- package: github.com/gogo/protobuf
  version: v0.4
```
