### ISSUE TITLE
Overcoming Dependency Conflicts

### ISSUE THREAD

**Issue by frankgreco** [kubernetes/client-go#174]
I have been trying to get some code to compile over the past few days and cannot seem to get it to work. 

What is the correct version/commit combination for the following packages so that `glide update && glide install && go build` work?

* `k8s.io/kubernetes`
* `k8s.io/apimachinery`
* `k8s.io/client-go`

I have tried countless combinations and each time have gotten one of the following errors:

1. `[WARN]	Conflict: k8s.io/apimachinery rev is currently <some hash>, but k8s.io/client-go wants <a different hash>`
2. `controller/controller.go:57: cannot use ".../vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type ".../vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type ".../vendor/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value`

**Comment by ericchiang** [comment]
Are you following the instructions here? https://github.com/kubernetes/client-go/blob/master/INSTALL.md#glide

Do you have a glide.yaml file you could share that's failing?

**Comment by frankgreco** [comment]
Here's one of my combinations:

I did follow the instructions above. The issue though is that `v2.0.0` doesn't play nicely with all versions of `apimachinery` or `k8s.io/kubernetes`. For example:

`[WARN]	Conflict: k8s.io/client-go rev is currently v2.0.0, but k8s.io/apiserver wants dabf37f5df16a224729883d9f616ce4a2c282e95`

```yaml
package: path/to/project
import:
- package: github.com/Sirupsen/logrus
  version: 0.11.5
- package: github.com/gorilla/mux
  version: v1.3.0
- package: github.com/spf13/cobra
- package: golang.org/x/net
  subpackages:
  - context
- package: k8s.io/kubernetes
  version: 1.6.0
  subpackages:
  - pkg/client/unversioned
  - pkg/kubectl/cmd/util
  - pkg/apis/extensions
  - pkg/api
  - pkg/client/clientset_generated/internalclientset
- package: k8s.io/apimachinery
  version: c1c4a7fe832857c75cc1d79c8e40d71d5da15fc6
  subpackages:
  - pkg/apis/meta/v1
  - pkg/api/errors
- package: k8s.io/client-go
  version: v2.0.0
  subpackages:
  - rest

```

**Comment by ericchiang** [comment]
The compatibility matrix in the README implies that v2.0.0 isn't compatible with v1.6.0 https://github.com/kubernetes/client-go#compatibility-matrix

Why do you need to specify versions for `k8s.io/kubernetes` and `k8s.io/apimachinery`. Why not use the version `client-go` wants?

**Comment by frankgreco** [comment]
@ericchiang that doesn't seem to work.

The following `glide.yaml` file produces the following error:

```yaml
package: git.nmlv.nml.com/Epitropos/kanali
import:
- package: github.com/Sirupsen/logrus
  version: 0.11.5
- package: github.com/gorilla/mux
  version: v1.3.0
- package: github.com/spf13/cobra
- package: golang.org/x/net
  subpackages:
  - context
- package: k8s.io/kubernetes
  subpackages:
  - pkg/client/unversioned
  - pkg/kubectl/cmd/util
  - pkg/apis/extensions
  - pkg/api
  - pkg/client/clientset_generated/internalclientset
- package: k8s.io/apimachinery
  subpackages:
  - pkg/apis/meta/v1
  - pkg/api/errors
- package: k8s.io/client-go
  version: v2.0.0
  subpackages:
  - rest

```

```sh
[ERROR]	Error scanning k8s.io/client-go/util/flowcontrol: open /Users/gre9521/.glide/cache/src/https-k8s.io-client-go/util/flowcontrol: no such file or directory
[ERROR]	This error means the referenced package was not found.
[ERROR]	Missing file or directory errors usually occur when multiple packages
[ERROR]	share a common dependency and the first reference encountered by the scanner
[ERROR]	sets the version to one that does not contain a subpackage needed required
[ERROR]	by another package that uses the shared dependency. Try setting a
[ERROR]	version in your glide.yaml that works for all packages that share this
[ERROR]	dependency.

[WARN]	Conflict: k8s.io/client-go rev is currently v2.0.0, but k8s.io/apiserver wants 623dbc3dc4e22ddd57b7d1d73b9afa9c9448e8f5
```
