### ISSUE TITLE
oidc cache key is uniqueness

### ISSUE THREAD

**Issue by mailtokun** [kubernetes/client-go#213]
I have more then 3 kubernetes clusters. 
Below is my code, 
```
package main

import (
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/client-go/kubernetes"
	_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
	meta "k8s.io/apimachinery/pkg/apis/meta/v1"
	"fmt"
)

func  GetNodes(configPath string)  {
	fmt.Println("-------------------"+configPath+"-------------------------")
	config, err := clientcmd.BuildConfigFromFlags("", configPath)
	fmt.Println(err)
	clientSet, err := kubernetes.NewForConfig(config)
	fmt.Println(err)
	nodes ,err := clientSet.CoreV1().Nodes().List(meta.ListOptions{})
	fmt.Println(err)
	fmt.Println(len(nodes.Items))
}
func  main ()  {
	GetNodes("/Users/administrator/Downloads/cluster1/config")
	GetNodes("/Users/administrator/Downloads/cluster2/config")
	GetNodes("/Users/administrator/Downloads/cluster3/config")
}
```

Here is output:
```
-------------------/Users/administrator/Downloads/cluster1/config-------------------------
<nil>
<nil>
<nil>
1
-------------------/Users/administrator/Downloads/cluster2/config-------------------------
<nil>
<nil>
<nil>
1
-------------------/Users/administrator/Downloads/cluster3/config-------------------------
<nil>
<nil>
Forbidden: "/api/v1/nodes" (get nodes)
0
```

If I change the cluster order, still work for first two clusters. The rest cluster doesn't work.
```
package main

import (
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/client-go/kubernetes"
	_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
	meta "k8s.io/apimachinery/pkg/apis/meta/v1"
	"fmt"
)

func  GetNodes(configPath string)  {
	fmt.Println("-------------------"+configPath+"-------------------------")
	config, err := clientcmd.BuildConfigFromFlags("", configPath)
	fmt.Println(err)
	clientSet, err := kubernetes.NewForConfig(config)
	fmt.Println(err)
	nodes ,err := clientSet.CoreV1().Nodes().List(meta.ListOptions{})
	fmt.Println(err)
	fmt.Println(len(nodes.Items))
}
func  main ()  {
	GetNodes("/Users/administrator/Downloads/cluster3/config")
	GetNodes("/Users/administrator/Downloads/cluster2/config")
	GetNodes("/Users/administrator/Downloads/cluster1/config")
}
```

Here is output:
```
-------------------/Users/administrator/Downloads/cluster3/config-------------------------
<nil>
<nil>
<nil>
1
-------------------/Users/administrator/Downloads/cluster2/config-------------------------
<nil>
<nil>
<nil>
1
-------------------/Users/administrator/Downloads/cluster1/config-------------------------
<nil>
<nil>
Forbidden: "/api/v1/nodes" (get nodes)
0
```

**Comment by mailtokun** [comment]
@caesarxuchao Could you have a look?

**Comment by caesarxuchao** [comment]
That's strange. What is you do?
```
ListAllNodes("/home/cluster1/config")
ListAllNodes("/home/cluster1/config")
ListAllNodes("/home/cluster1/config")
ListAllNodes("/home/cluster1/config")
ListAllNodes("/home/cluster1/config")
```

**Comment by mailtokun** [comment]
@caesarxuchao 
I would like to list nodes of each clusters(cluster1,cluster2,cluster3).

**Comment by mailtokun** [comment]
@caesarxuchao 
Is this a bug for clientcmd ?

**Comment by mailtokun** [comment]
@ericchiang 
Could you have a look as well?  Is this caused by oidc?

**Comment by mailtokun** [comment]
I got the root cause. oidc.go use client-id and idp-issuer-url as the key of OIDCAuthProvider.
My cluster 1 and cluster3 has same client-id and idp-issuer-url value in kubeconfig file.But cluster1 and cluster3 not belong to same user.
@ericchiang
Do you have any idea?

## cluster1's kubeconfig
```     
 name: oidc
      config:
        client-id: client1
        client-secret: client1
        id-token: asdfasdfasdfasdf.adsfasdfadsf.fTMSiJh2Uu0KTxesQ-asdfasdfasdf-asdfadsfasdf-asdfasdfasdfa
        idp-issuer-url: https://iam.mywebsite.net/k8s
        refresh-token: asdfasdfasdf-asdfasdfas-asdfasdf-asdfasdf-asdfasdf-asdfasdfasd==
```

## cluster3's kubeconfig
```
      name: oidc
      config:
        client-id: client1
        client-secret: client1
        id-token: yyyeuii.adsfasdfadsf.asd-asdfasdfasdf-asdfadsfasdf-asdfasdfasdfa
        idp-issuer-url: https://iam.mywebsite.net/k8s
        refresh-token: yyyywerwe-asdfasdfas-asdfasdf-asdfasdf-asdfasdf-asdfasdfasd==
```
