### ISSUE TITLE
Use InClusterConfig but allow master IP to be overwritten?

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/client-go#281]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
When trying to deploy kube-proxy DaemonSet with service account, I found [`InClusterConfig()`](https://github.com/kubernetes/client-go/blob/v4.0.0/rest/config.go#L305-L309) not usable for kube-proxy, as this function sets master's IP to kubernetes service's VIP, which depends on kube-proxy itself to set up the proxy rules first...

At this point, in order to use service account on kube-proxy, we have to carry the responsibility of provisioning kube-proxy's kubeconfig at cluster deployment level, like [what kubeadm does](https://github.com/kubernetes/kubernetes/blob/b8fde17fc2135b6639922c5861db13fc934ac328/cmd/kubeadm/app/phases/addons/proxy/manifests.go#L20-L49):
```
  kubeconfig.conf: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: {{ .MasterEndpoint }}
      name: default
    contexts:
    - context:
        cluster: default
        namespace: default
        user: default
      name: default
    current-context: default
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
```

(Or alternatively we may be able to overwrite the [`Host` field](https://github.com/kubernetes/client-go/blob/v4.0.0/rest/config.go#L329) after calling `InClusterConfig`?)

**What you expected to happen**:
I would like to have a supported way to generate in-cluster config for components like kube-proxy. Probably something like `InClusterProxyConfig(host string)`?

**How to reproduce it (as minimally and precisely as possible)**:
See https://github.com/kubernetes/kubernetes/pull/51172#discussion_r134681904.

cc @luxas @murali-reddy
