### ISSUE TITLE
Writing out a config object duplicates CA data and key data

### ISSUE THREAD

**Issue by sstarcher** [kubernetes/client-go#458]
Using a small snippet like
```
	loader := clientcmd.NewDefaultClientConfigLoadingRules()

	client, err := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loader, &clientcmd.ConfigOverrides{}).RawConfig()
	if e != nil {
		return e
	}

	err = clientcmd.WriteToFile(client, kubeConfigPath))
```

If the kubeconfig contains `certificate-authority-data` or `client-certificate-data` that data will be duplicated.

Example data
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: YWJjCg==
    server: https://api.test.com
  name: test.com
```

CA data is `abc` initially.  After one run you get 

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: YWJjCmFiYwo=
    server: https://api.test.com
  name: test.com
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```

Which is 
```
abc
abc
```

This of course happens continuously every run.  The data is correctly loaded, but when serialised to a file it looks to be appending to the base64 encoded data.
