### ISSUE TITLE
Copy of 16M+ file to container causes invalid data frame error

### ISSUE THREAD

**Issue by maorfr** [kubernetes/client-go#460]
Hello,

We have been trying to implement a copy mechanism in to a container.
We are using this code:

```
stdin := bytes.NewReader(byteArray)
req := clientset.Core().RESTClient().Post().
	Resource("pods").
	Name("podName").
	Namespace("namespace").
	SubResource("exec")
scheme := runtime.NewScheme()
check(err)

parameterCodec := runtime.NewParameterCodec(scheme)
req.VersionedParams(&core_v1.PodExecOptions{
	Command:   strings.Fields("cp /dev/stdin /tmp/file"),
	Container: containerName,
	Stdin:     stdin != nil,
	Stdout:    true,
	Stderr:    true,
	TTY:       false,
}, parameterCodec)

exec, err := remotecommand.NewSPDYExecutor(config, "POST", req.URL())
check(err)

var stdout, stderr bytes.Buffer
err = exec.Stream(remotecommand.StreamOptions{
	Stdin:  stdin,
	Stdout: &stdout,
	Stderr: &stderr,
	Tty:    false,
})
check(err)
```

The complete code can be found [here](https://github.com/maorfr/skbn/blob/master/pkg/skbn/kube.go)

We noticed that when trying to copy a file which is 16M and up, the action is not successful and we get an output of `E0904 12:56:33.953212   15894 v2.go:105] invalid data frame`.

Any file that is under 16M (16777215 and less) is being copied without any error.

Can anyone help on this?

Thanks in advance!

**Comment by deads2k** [comment]
@liggitt size seems suspicious compared to recent fixes.

**Comment by liggitt** [comment]
What version of client-go and apiserver is this seen with?

**Comment by maorfr** [comment]
@deads2k @liggitt thanks for the quick response!

Current versions (from [glide.yaml](https://github.com/maorfr/skbn/blob/master/glide.yaml)):
```
- package: k8s.io/api
  version: kubernetes-1.11.2
  subpackages:
  - core/v1
- package: k8s.io/apimachinery
  version: kubernetes-1.11.2
  subpackages:
  - pkg/apis/meta/v1
- package: k8s.io/client-go
  version: kubernetes-1.11.2
  subpackages:
  - kubernetes
  - rest
  - tools/clientcmd
```

But we have also tried it with:
```
- package: k8s.io/api
  subpackages:
  - core/v1
- package: k8s.io/apimachinery
  subpackages:
  - pkg/apis/meta/v1
- package: k8s.io/client-go
  version: v8.0.0
  subpackages:
  - kubernetes
  - rest
  - tools/clientcmd
```

And got the same results.

Thanks again :)
