### ISSUE TITLE
Convert object to kubernetes manifest

### ISSUE THREAD

**Issue by HankZhengg** [kubernetes/client-go#533]
Hi ,

Is there exist way to convert an object to kubernetes manifest. For example

From:
```
type email struct{
     name string
     kind string
     image string
}
e:= email {
      name:email,
      kind:Deployment,
      image:email-service:version-1.9.1
}
```
To:
```
kind: Deployment
metadata:
  name: email
...
  image: email-service:version-1.9.1
```
