### ISSUE TITLE
ThirdPartyResources TypeMeta empty?

### ISSUE THREAD

**Issue by yvespp** [kubernetes/client-go#60]
While using ThirdPartyResources together with Informer I noticed that sometimes the Kind and APIVersion are missing.

I wrote a little test app based on the ThirdPartyResources and Informer examples to reproduce the issue. Source: https://github.com/yvespp/tpr-example
Here is the output of the app:

```
lodur:tpr-example yves$ $GOPATH/bin/tpr-example -kubeconfig ~/.kube/config 
SKIPPING: already exists &v1beta1.ThirdPartyResource{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"example.k8s.io", GenerateName:"", Namespace:"", SelfLink:"/apis/extensions/v1beta1/thirdpartyresourcesexample.k8s.io", UID:"98135044-d69c-11e6-9758-165fba9cabe3", ResourceVersion:"12807", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:63619584673, nsec:0, loc:(*time.Location)(0x15d1720)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Description:"An Example ThirdPartyResource", Versions:[]v1beta1.APIVersion{v1beta1.APIVersion{Name:"v1"}}}
GET: main.Example{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, Metadata:v1.ObjectMeta{Name:"example1", GenerateName:"", Namespace:"default", SelfLink:"/apis/k8s.io/v1/namespaces/default/examples/example1", UID:"c6f43676-d6a7-11e6-9758-165fba9cabe3", ResourceVersion:"18219", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:63619589476, nsec:0, loc:(*time.Location)(0x15d1720)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:main.ExampleSpec{Foo:"hello", Bar:true}}
LIST: main.ExampleList{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, Metadata:v1.ListMeta{SelfLink:"/apis/k8s.io/v1/examples", ResourceVersion:"18804"}, Items:[]main.Example{main.Example{TypeMeta:v1.TypeMeta{Kind:"Example", APIVersion:"k8s.io/v1"}, Metadata:v1.ObjectMeta{Name:"example1", GenerateName:"", Namespace:"default", SelfLink:"/apis/k8s.io/v1/namespaces/default/examples/example1", UID:"c6f43676-d6a7-11e6-9758-165fba9cabe3", ResourceVersion:"18219", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:63619589476, nsec:0, loc:(*time.Location)(0x15d1720)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:main.ExampleSpec{Foo:"hello", Bar:true}}}}
Starting watch!
listing examples from store:
CREATED: default/example1, APIVersion: k8s.io/v1, Kind: Example
UPDATED:
  old: default/example1, APIVersion: k8s.io/v1, Kind: Example
  new: default/example1, APIVersion: k8s.io/v1, Kind: Example
UPDATED:
  old: default/example1, APIVersion: k8s.io/v1, Kind: Example
  new: default/example1, APIVersion: k8s.io/v1, Kind: Example
UPDATED:
  old: default/example1, APIVersion: k8s.io/v1, Kind: Example
  new: default/example1, APIVersion: k8s.io/v1, Kind: Example
UPDATED:
  old: default/example1, APIVersion: k8s.io/v1, Kind: Example
  new: default/example1, APIVersion: k8s.io/v1, Kind: Example
DELETED: default/example1, APIVersion: , Kind: 
CREATED: default/example1, APIVersion: , Kind: 
UPDATED:
  old: default/example1, APIVersion: , Kind: 
  new: default/example1, APIVersion: , Kind: 
UPDATED:
  old: default/example1, APIVersion: , Kind: 
  new: default/example1, APIVersion: , Kind: 
UPDATED:
  old: default/example1, APIVersion: , Kind: 
  new: default/example1, APIVersion: , Kind: 
^Creceived signal 2, exiting...
```

As you can see, the first create and update events have the TypeMeta but all events starting form the DELETED event have no TypeMeta.
The first resource get's created in the code, the DELETED and CREATED events come from these commands:
```
kubectl delete -f example.yaml 
kubectl create -f example.yaml 
```
I used the client from [HEAD](https://github.com/kubernetes/client-go/commit/24a02a6d7d2c9a21b12a3eb35c71c784e63825f4) but originally run into the problem with the v1.5.0 and Kubernetes 1.4.7.

Are there some issues with the test code or is this a bug?
