### ISSUE TITLE
Is it possible to post a declarative yaml to create recourse such as daemonset or deployment

### ISSUE THREAD

**Issue by DeadEyE1102** [kubernetes/client-go#706]
As I saw the example of "create-update-delete-deployment", in that case, we declare the recourse in this way:
```
deployment := &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{
			Name: "daemonset-example",
		}
```

I was wondering if we can just organize an yaml file in string type first and send it via POST method by client-go.
such as:
```
deploymentYaml := `
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: daemonset-example
spec:
  template:
    metadata:
      labels:
        app: daemonset-example
    spec:
      containers:
      - name: daemonset-example
        image: ubuntu:trusty
        command:
        - /bin/sh
        args:
        - -c
        - >-
          while [ true ]; do
          echo "DaemonSet running on $(hostname)" ;
          sleep 10 ;
          done
`
req, err := http.NewRequest("POST", url, bytes.NewBuffer(deploymentYaml))
```
