### ISSUE TITLE
tools/clientcmd: Example_mergingSomeWithConflict fails with Golang 1.14 beta1

### ISSUE THREAD

**Issue by eclipseo** [kubernetes/client-go#744]
Fedora rawhide with Go 1.14 beta1, client-go 1.17.2:

```
k8s.io/client-go/tools/clientcmd
--- FAIL: Example_mergingSomeWithConflict (0.00s)
got:
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://a-different-cow.org:8080
  name: cow-cluster
- cluster:
    insecure-skip-tls-verify: true
    server: http://donkey.org:8080
  name: donkey-cluster
contexts:
- context:
    cluster: cow-cluster
    namespace: hammer-ns
    user: red-user
  name: federal-context
current-context: federal-context
kind: Config
preferences: {}
users:
- name: red-user
  user:
    token: a-different-red-token
- name: yellow-user
  user:
    token: yellow-token
want:
apiVersion: v1
clusters:
- cluster:
    server: http://cow.org:8080
  name: cow-cluster
- cluster:
    insecure-skip-tls-verify: true
    server: http://donkey.org:8080
  name: donkey-cluster
contexts:
- context:
    cluster: cow-cluster
    namespace: hammer-ns
    user: red-user
  name: federal-context
current-context: federal-context
kind: Config
preferences: {}
users:
- name: red-user
  user:
    token: red-token
- name: yellow-user
  user:
    token: yellow-token
FAIL
exit status 1
FAIL	k8s.io/client-go/tools/clientcmd	0.036s
```
