### ISSUE TITLE
Config not found with Kubectl.exe on Cygwin

### ISSUE THREAD

**Issue by lsambolino** [kubernetes/client-go#767]
Hi, I see an issue with kubectl (GitVersion1.17.0, GoVersion go1.13.4) from a Cygwin 3.1.4 installation over Windows 10. I assume this is the correct place to report as relates to the go client.
 
I have issues with let kubectl read config config files correctly.
When trying to launch `kubectl cluster-info` I obtain the following:
```
W0320 11:25:18.677337    9196 loader.go:223] Config not found: /home/myname/.kubectlconf_ec2.yaml
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
```

Steps to reproduce: 

1. Install Cygwin 3.1.4 on Windows

2. Download kubectl on your home directory through `curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/windows/amd64/kubectl.exe`

3. Create a simple .yaml file in your home directory, as for example: 

```
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQC3RT1F1C4T34UTH0RIT1D4T4tLQo=
    server: https://yourkubernetesserverurl
  name: ec2
contexts:
- context:
    cluster: ec2
    namespace: default
    user: yourusername-ec2
  name: ec2
current-context: ec2
preferences: {}
users:
- name: yourusername-ec2
  user:
    auth-provider:
      config:
        client-id: loginapp
        client-secret: 4TORGiNVCL13N753CR376hUjfjr
        id-token: eyJhbGci1D70K3ND4746eU4maf8hh2zz4EENQ
        idp-issuer-url: https://dex.dev.youcompanydomain/dex
        refresh-token: Chlmr3fr35ht0k3nd474NG1p
      name: oidc
```

4. Edit the .bashrc file in your home directory to add the following line:
export KUBECONFIG=~/.kubectlconf_ec2.yaml

5. Source the file through `source .bashrc`

6.  Launch a kubectl get command as example `kubectl --context=ec2 get deployments, statefulset

7. Obtain the Error:
```
W0320 14:14:26.293912   18648 loader.go:223] Config not found: /home/yourusername/.kubectlconf_ec2.yaml
context "ec2" does not exist
context "ec2" does not exist
```
Is this expected behavior ? Am I missing something ?
Thank you
