### ISSUE TITLE
Getting current namespace from the pod

### ISSUE THREAD

**Issue by alekc** [kubernetes/client-go#804]
What's the best way of getting the namespace in case of using `rest.inClusterConfig`?

As far as I can see, `*rest.Config` doesn't expose such information, and it looks like the "easiest" way to get such info is to read contents of `/var/run/secrets/kubernetes.io/serviceaccount/namespace`

Is there a better way? Or, if there is not, should we expose such information in `*rest.Config`?

**Comment by FrelDX** [comment]
Connect pod through SSH protocol  https://github.com/FrelDX/kube-console-on-ssh

**Comment by FrelDX** [comment]
![image](https://user-images.githubusercontent.com/32826879/83704156-e3050c80-a643-11ea-9cff-90ff1a526f8b.png)

**Comment by maxsxu** [comment]
Using the [kubernetes downward api](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api)

```
spec:
  containers:
   - env:
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
```
