### ISSUE TITLE
ResourceQuota can only create one at a time

### ISSUE THREAD

**Issue by yyf1986** [kubernetes/client-go#822]
when I use client-go to create quota, the code like this
```
deploy, err := res.ParseQuantity("2")
	res := &apiv1.ResourceQuota{
		//TypeMeta:   metav1.TypeMeta{},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "ssss",
			Namespace: "default",
		},
		Spec: apiv1.ResourceQuotaSpec{
			Hard: apiv1.ResourceList{"count/deployments.apps": deploy,
			},

		},
		Status: apiv1.ResourceQuotaStatus{},
	}
```
Hard is not a list,when I set more than one , I should create more than one.

when I use yaml to create like this
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-demo
spec:
  hard:
    pods: "2"
    cpu: "2"
    memory: 2Gi 
```
I can set more than one
