### ISSUE TITLE
Programmatically created Job does not start 

### ISSUE THREAD

**Issue by ThomasVictoria** [kubernetes/client-go#909]
Hello, I'm using minikube and I' trying to programmatically launch jobs from my code.

I am creating a Job with the client as following: 
```go
// creates the in-cluster config
config, err := rest.InClusterConfig()
if err != nil {
	panic(err.Error())
}
// creates the clientset
clientset, err := kubernetes.NewForConfig(config)
if err != nil {
	panic(err.Error())
}

jobsClient := clientset.BatchV1().Jobs("myproject")

BackoffLimit := new(int32)
*BackoffLimit = 1

TTLSecondsAfterFinished := new(int32)
*TTLSecondsAfterFinished = 120

job := &batchv1.Job{
	TypeMeta: metav1.TypeMeta{
		Kind:       "Job",
		APIVersion: "batch/v1",
	},
	ObjectMeta: metav1.ObjectMeta{
		Name:      "worker",
		Namespace: "myproject",
	},
	Spec: batchv1.JobSpec{
		BackoffLimit:            BackoffLimit,
		TTLSecondsAfterFinished: TTLSecondsAfterFinished,
		Template: apiv1.PodTemplateSpec{
			Spec: apiv1.PodSpec{
				Volumes: []apiv1.Volume{
					{
						Name: "shared",
					},
				},
				Containers: []apiv1.Container{
					{
						Name:            "worker",
						Image:           "worker:latest",
						ImagePullPolicy: apiv1.PullNever,
						Command:         []string{"echo", "\"test\""},
						VolumeMounts: []apiv1.VolumeMount{
							{
								Name:      "shared",
								MountPath: "/shared",
							},
						},
					},
				},
			},
		},
	},
}

result1, err1 := jobsClient.Create(context.TODO(), job, metav1.CreateOptions{})

if err != nil {
	fmt.Println(err1)
	panic(err1)
}

fmt.Printf("Created job %q.\n", result1)
```

Also I have this code defining the role I apply on the pod supposed to start the job.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-creator
  namespace: myproject
  labels:
    run: api
secrets:
  - name: pod-creator-token

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-launch-role
  namespace: myproject
rules:
- apiGroups: ["v1"]
  resources: [jobs"]
  verbs: ["get", "list", "create", "update"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods-svc-account
  namespace: myproject
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-launch-role
  apiGroup: rbac.authorization.k8s.io
```

And get this result from the logs

<img width="1381" alt="Screen Shot 2020-12-21 at 8 05 43 PM" src="https://user-images.githubusercontent.com/7486950/102770724-f43b1e00-43c7-11eb-90fa-ea7992fd4c81.png">

It looks like the job was successfully launched but I don't see any job in my cluster, so in fact it didn't start. I can't figure out what could be missing. It's been two days I'm stuck on this and I ran out of solutions. Any ideas of what could be wrong ?
