### ISSUE TITLE
dynamic patch can not remove nodeselector labels?

### ISSUE THREAD

**Issue by qiangshui** [kubernetes/client-go#922]
kubernetes version: 1.15.10 
client-go version: v0.15.10

Can not remove lebels from Deployment nodeSelector when the PatchType is MergePatchType or StrategicMergePatchType?

Here is part of the yaml example:
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: frontgateway
  name: frontgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: frontgateway
  template:
    metadata:
      labels:
        k8s-app: frontgateway
    spec:
      nodeSelector:
        CLUSTER: WX
        GROUP: IAD
```

patch code:
```
playLoadBytes,_ :=json.Marshal(unstructuredObj)
_,err=DynamicClient.Resource(mapping.Resource).Namespace(namespace).Patch(name,types.StrategicMergePatchType,playLoadBytes,metav1.PatchOptions{})
```

When I remove the line "CLUSTER: WX" from yaml file and execute patch() method,  deployment resource still has the "  CLUSTER: WX"  label, but add a new label could work.

I saw the official document [https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/](url),  it says `Notice that the tolerations list in the PodSpec was replaced, not merged. This is because the Tolerations field of PodSpec does not have a patchStrategy key in its field tag. So the strategic merge patch uses the default patch strategy, which is replace.`

So I check the field tag of NodeSelector in Kubernetes source code,:
 ```
NodeSelector map[string]string `json:"nodeSelector,omitempty" protobuf:"bytes,7,rep,name=nodeSelector"`
```
There is no "patchStrategy" tag, so why the patch() doesn't do the replace?
