### ISSUE TITLE
ClusterRole remains the same even after the update

### ISSUE THREAD

**Issue by life1347** [kubernetes/client-go#953]
**_k8s.io/client-go: v0.18.9_**
**server version: test both on v1.17.3/v1.18.17**

I tried to update rules of a ClusterRole from

**old rule set**
```
rules:
- apiGroups:
  - management.dummy.crd
  resourceNames:
  - dummyuser
  resources:
  - users
  verbs:
  - get
- apiGroups:
  - management.dummy.crd
  resources:
  - containerresources
  verbs:
  - get
```

to

**new rule set**
```
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
```

I expect that the user should be able to access all resource after the update. After using client-go API to update the ClusterRole with new rule set, the user `dummyuser` is now able to access all resources.

However, `kubectl get clusterrole <name> -o yaml` still returns the old rule set.

Is this a bug or anything I missed? If it's not a bug, what is the correct way to update a ClusterRole? 

Thanks
